# References
# - on chosing your Python base container
#   https://pythonspeed.com/articles/base-image-python-docker-images/
#   https://stackoverflow.com/questions/52740556/python-3-7-docker-images

FROM python:3.10

RUN set -ex \
  && git clone https://github.com/VCityTeam/py3dtilers.git \
  && mv py3dtilers/ py3dtilers.git \
  && cd py3dtilers.git \
  && git checkout 5a243d07097e1b25edf848eae107d3d630fcaf13 \ 
  && pip3 install -e .

WORKDIR py3dtilers.git/
