#Download base image 
ARG UBUNTU_VERSION=20.04
FROM ubuntu:${UBUNTU_VERSION} as base
# LABEL about the custom image
LABEL maintainer="msalazar@centrogeo.edu.mx"
LABEL version="0.0.1"
LABEL description="This Docker is for the Dgtal library installation."
ARG DEBIAN_FRONTEND=noninteractive



###Update 
RUN apt-get update && apt-get install -y curl

##### Basics
RUN apt install -y build-essential
#### Install Git
RUN apt install -y git 
#### Install G++ 
RUN apt install g++


#### gl libraries
RUN apt -y update --fix-missing
#RUN apt -y install libx11-dev 
RUN apt -y install mesa-common-dev libglm-dev mesa-utils


### Install cmake
RUN apt -y install cmake 
###Install boost 
RUN apt -y  install  libboost-all-dev
###Install clang-9
RUN apt -y install clang-9

RUN apt -y install libcgal*

RUN apt -y install libmagick++-dev

RUN apt -y install graphicsmagick*

RUN apt -y install doxygen

RUN apt -y install libcgal-dev

RUN apt -y install libinsighttoolkit4-dev

RUN apt -y install libqglviewer-dev-qt5

RUN apt -y install libgmp-dev

RUN  apt -y install libeigen3-dev

RUN  apt -y install libfftw3-dev

#### User to install 
RUN groupadd -g 1000 digital
RUN useradd -d /home/digital -s /bin/bash -m digital -u 1000 -g 1000
RUN usermod -aG sudo digital
####

RUN apt -y install mesa-common-dev libglm-dev mesa-utils

### Directory to  store the git 
RUN mkdir /home/digital/git/
RUN mkdir /home/digital/git/DGtal


#### clone git and install 
RUN git clone https://github.com/DGtal-team/DGtal.git /home/digital/git/DGtal \
    && cd /home/digital/git/DGtal \
    && git checkout 77bd36304

RUN mkdir /home/digital/git/DGtal/build 
RUN cd /home/digital/git/DGtal/build &&  cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_GMP=true -DWITH_EIGEN=true -DWITH_FFTW3=true -DWITH_CGAL=true -DWITH_ITK=true -DWITH_OPENMP=true -DWITH_CAIRO=true -DWITH_QGLVIEWER=true -DWITH_MAGICK=true && make install

####################################################################

### added for GRIM : DGtalTools

RUN git clone https://github.com/DGtal-team/DGtalTools.git /home/digital/git/DGtalTools \
    && cd /home/digital/git/DGtalTools \
    && git checkout ad8e3c8

RUN mkdir /home/digital/git/DGtalTools/build
RUN cd /home/digital/git/DGtalTools/build &&  cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_ITK=true  && make install

####################################################################

### added for GRIM : pc2vol with libigl 2.5.0 and cgal 5.0.2 system

# DIRTY - TO BE CLEANED !!!!!!!!!!!!!!!!! notamment purger cgal systeme
# # install requirements
# RUN apt update \
#     && apt install -y xorg-dev libglu1-mesa-dev \
#     && apt install -y wget
# RUN mkdir /home/pc2vol \
#     && cd /home/pc2vol \
#     && wget https://cmake.org/files/v3.19/cmake-3.19.8-Linux-x86_64.tar.gz \
#     && tar -xzf cmake-3.19.8-Linux-x86_64.tar.gz
# 
# # build pc2vol
# RUN cd /home/pc2vol \
#     && git clone https://github.com/dcoeurjo/pc2vol \
#     && cd pc2vol && git checkout 866bd0b \
#     && mkdir build && cd build \
#     && /home/pc2vol/cmake-3.19.8-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=Release -DWITH_LIBIGL=ON  -DWITH_CGAL=ON  -DWITH_GMP=ON  .. \
#     && /home/pc2vol/cmake-3.19.8-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=Release -DWITH_LIBIGL=ON  -DWITH_CGAL=ON  -DWITH_GMP=ON  .. \
#     && make
#     ## cmake must be called 2 times because of a bug in cmake
#     ## MAYBE NOT - MANUAL INSTALL OF LIBIGL 2.5.0 REMOVED - RETRY WITH ONLY
#     ## ONE CALL TO CMAKE

####################################################################

### added for GRIM : pc2vol with libigl 2.5.0 and cgal 5.5.3

# install requirements
RUN apt update \
    && apt install -y xorg-dev libglu1-mesa-dev \
    && apt install -y wget
RUN mkdir /home/pc2vol \
    && cd /home/pc2vol \
    && wget https://cmake.org/files/v3.19/cmake-3.19.8-Linux-x86_64.tar.gz \
    && tar -xzf cmake-3.19.8-Linux-x86_64.tar.gz
RUN apt install -y unzip \
    && apt purge -y libcgal* \
    && cd /tmp \
    && wget https://github.com/CGAL/cgal/releases/download/v5.5.3/CGAL-5.5.3.zip \
    && cd && unzip /tmp/CGAL-5.5.3.zip

# build pc2vol
RUN cd /home/pc2vol \
    && export CGAL_DIR=/root/CGAL-5.5.3 \
    && git clone https://github.com/dcoeurjo/pc2vol \
    && cd pc2vol && git checkout 92ee823 \
    && mkdir build && cd build \
    && /home/pc2vol/cmake-3.19.8-Linux-x86_64/bin/cmake  -DCMAKE_BUILD_TYPE=Release  -DWITH_LIBIGL=ON  -DWITH_CGAL=ON  -DWITH_GMP=ON  .. \
    && make

####################################################################

### added for GRIM : pc2vol with libigl 2.5.0 and cgal 4.12.x

# # install requirements
# RUN apt update \
#     && apt install -y xorg-dev libglu1-mesa-dev \
#     && apt install -y wget
# RUN mkdir /home/pc2vol \
#     && cd /home/pc2vol \
#     && wget https://cmake.org/files/v3.19/cmake-3.19.8-Linux-x86_64.tar.gz \
#     && tar -xzf cmake-3.19.8-Linux-x86_64.tar.gz
# RUN apt install -y unzip \
#     && apt purge -y libcgal* \
#     && cd /tmp \
#     && wget https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.12.2/CGAL-4.12.2.zip \
#     && cd && unzip /tmp/CGAL-4.12.2.zip \
#     && cd /root/CGAL-4.12.2 \
#     && cmake  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/root/CGAL4122_bin   . \
#     && make \
#     && make install
# 
# # build pc2vol
# RUN cd /home/pc2vol \
#     && export CGAL_DIR=/root/CGAL4122_bin \
#     && git clone https://github.com/dcoeurjo/pc2vol \
#     && cd pc2vol && git checkout 866bd0b \
#     && mkdir build && cd build \
#     && /home/pc2vol/cmake-3.19.8-Linux-x86_64/bin/cmake  -DCMAKE_BUILD_TYPE=Release   -DWITH_LIBIGL=ON  -DWITH_CGAL=ON  -DWITH_GMP=ON  .. \
#     && make

####################################################################

### added for GRIM : pc2vol with libigl 2.4.0 and cgal 5.0.2 system

# ### libigl 2.4.0 should include cgal 4.12.x:
# ### see https://github.com/CGAL/cgal/commit/f7c3c8212b56c0d6dae63787efc99093f4383415
# ### but DOES NOT!!! Here cgal 5.0.2 system is used!!!
# 
# # install requirements
# RUN apt update \
#     && apt install -y xorg-dev libglu1-mesa-dev \
#     && apt install -y wget
# RUN mkdir /home/pc2vol \
#     && cd /home/pc2vol \
#     && wget https://cmake.org/files/v3.19/cmake-3.19.8-Linux-x86_64.tar.gz \
#     && tar -xzf cmake-3.19.8-Linux-x86_64.tar.gz
# 
# # build pc2vol
# RUN cd /home/pc2vol \
#     && git clone https://github.com/elombardi2/pc2vol \
#     && cd pc2vol && git checkout 0d84c52 \
#     && mkdir build && cd build \
#     && /home/pc2vol/cmake-3.19.8-Linux-x86_64/bin/cmake  -DCMAKE_BUILD_TYPE=Release -DWITH_LIBIGL=ON  -DWITH_CGAL=ON  -DWITH_GMP=ON  .. \
#     && make

####################################################################

### added for GRIM : pc2vol with libigl 2.4.0 and cgal 4.12.x

# # install requirements
# RUN apt update \
#     && apt install -y xorg-dev libglu1-mesa-dev \
#     && apt install -y wget
# RUN mkdir /home/pc2vol \
#     && cd /home/pc2vol \
#     && wget https://cmake.org/files/v3.19/cmake-3.19.8-Linux-x86_64.tar.gz \
#     && tar -xzf cmake-3.19.8-Linux-x86_64.tar.gz
# RUN apt install -y unzip \
#     && apt purge -y libcgal* \
#     && cd /tmp \
#     && wget https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.12.2/CGAL-4.12.2.zip \
#     && cd && unzip /tmp/CGAL-4.12.2.zip \
#     && cd /root/CGAL-4.12.2 \
#     && cmake  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/root/CGAL4122_bin . \
#     && make \
#     && make install
# 
# # build pc2vol
# RUN cd /home/pc2vol \
#     && export CGAL_DIR=/root/CGAL4122_bin \
#     && git clone https://github.com/elombardi2/pc2vol \
#     && cd pc2vol && git checkout 0d84c52 \
#     && mkdir build && cd build \
#     && /home/pc2vol/cmake-3.19.8-Linux-x86_64/bin/cmake  -DCMAKE_BUILD_TYPE=Release  -DWITH_LIBIGL=ON  -DWITH_CGAL=ON  -DWITH_GMP=ON  .. \
#     && make

####################################################################

### added for GRIM : pc2vol with libigl 2.4.0 and cgal 5.5.3

# # install requirements
# RUN apt update \
#     && apt install -y xorg-dev libglu1-mesa-dev \
#     && apt install -y wget
# RUN mkdir /home/pc2vol \
#     && cd /home/pc2vol \
#     && wget https://cmake.org/files/v3.19/cmake-3.19.8-Linux-x86_64.tar.gz \
#     && tar -xzf cmake-3.19.8-Linux-x86_64.tar.gz
# RUN apt install -y unzip \
#     && apt purge -y libcgal* \
#     && cd /tmp \
#     && wget https://github.com/CGAL/cgal/releases/download/v5.5.3/CGAL-5.5.3.zip \
#     && cd && unzip /tmp/CGAL-5.5.3.zip
# 
# # build pc2vol
# RUN cd /home/pc2vol \
#     && export CGAL_DIR=/root/CGAL-5.5.3 \
#     && git clone https://github.com/elombardi2/pc2vol \
#     && cd pc2vol && git checkout 0d84c52 \
#     && mkdir build && cd build \
#     && /home/pc2vol/cmake-3.19.8-Linux-x86_64/bin/cmake  -DCMAKE_BUILD_TYPE=Release  -DWITH_LIBIGL=ON  -DWITH_CGAL=ON  -DWITH_GMP=ON  .. \
#     && make

####################################################################

# TMP
#CMD vol2obj  /home/digital/git/DGtal/examples/samples/bunny-32.vol  /datademo/bunny.obj

####################################################################

# # build OBJ to OFF converter
# # untrustfull source !!!! DO NOT USE !!!
# RUN cd /home/pc2vol \
#     && git clone https://github.com/elombardi2/obj2off.git \
#     && cd obj2off \
#     && make

